### ISSUE TITLE
Q: How to load modules from eszip files?

### ISSUE THREAD

**Issue by mlafeldt** [denoland/eszip#72]
Similar to #15, I'm also looking for more information about actual usage of this library, especially on how to load modules from generated eszip files. My understanding is that the JS code inside lib/ only provides the primitives to a) turn ES modules into the eszip container format and b) parse generated eszip files. What I found a bit confusing is that b) seems to be limited to reading a container's content without being able to access modules themselves.

As far as I know, the only way to actually use/load modules from a eszip file is to write a custom loader using Rust, which is what [deno compile](https://github.com/denoland/deno/blob/main/cli/standalone.rs) does. Please correct me if I'm wrong.

The main reason why I'm asking: [Netlify seems to use eszip to bundle code in different stages](https://github.com/mlafeldt/netlify-edge-bootstrap/blob/bundle/playground/bundle.ts), which makes me think that they must be using some custom Deno loader code behind the scenes. Without it, there seems to be no way to make use of the generated stage files other than writing my own loader in Rust, right? 🤔

**Comment by bartlomieju** [comment]
Currently `eszip` is an internal utility and there's no way to load files from it using Deno - the only way would be to compile a binary yourself and add a custom loader as you've noticed.

What is your use case for eszips?

**Comment by lucacasonato** [comment]
> The main reason why I'm asking: [Netlify seems to use eszip to bundle code in different stages](https://github.com/mlafeldt/netlify-edge-bootstrap/blob/bundle/playground/bundle.ts), which makes me think that they must be using some custom Deno loader code behind the scenes. Without it, there seems to be no way to make use of the generated stage files other than writing my own loader in Rust, right?

@mlafeldt Netlify uses [Deno Deploy Subhosting](https://deno.com/deploy/subhosting) to execute their Edge Functions. Deno Deploy Subhosting has the ability to load multi layered eszip files.

**Comment by mlafeldt** [comment]
> Deno Deploy Subhosting has the ability to load multi layered eszip files.

That's good to know! Now it makes sense.

In the meantime, I was able to [mimic Netlify's stage loaders without using eszip](https://github.com/mlafeldt/netlify-edge-bootstrap/commit/afd76cc340356a6d5956d5300e93082e0b9af4ef). (I might still write a Rust loader in the future just out of curiosity.)

Ah, and I also found this hidden gem in the repo:

```
❯ deno run -A --no-check https://raw.githubusercontent.com/denoland/eszip/main/lib/eszip.ts ls playground/stage1.eszip
Loading eszip v2
https://deno.land/std@0.114.0/datetime/mod.ts
netlify:bootstrap-stage1
...
```

So I'm good. 😄  Thank you both for your help.
